name: Build Android APK (Interval Runner)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Gradle 8.7
        run: |
          curl -sL https://services.gradle.org/distributions/gradle-8.7-bin.zip -o gradle.zip
          unzip -q gradle.zip -d $HOME/gradle
          echo "$HOME/gradle/gradle-8.7/bin" >> $GITHUB_PATH

      - name: Accept licenses & install Android 34 packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Generate Android project files
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p app/src/main/java/com/craig/intervalrunner
          mkdir -p app/src/main/res/{drawable,mipmap-anydpi-v26,values}
          touch build.gradle.kts

          cat > settings.gradle.kts <<'EOF'
          pluginManagement {
            repositories { gradlePluginPortal(); google(); mavenCentral() }
            plugins {
              id("com.android.application") version "8.4.2"
              id("org.jetbrains.kotlin.android") version "1.9.24"
            }
          }
          dependencyResolutionManagement {
            repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
            repositories { google(); mavenCentral() }
          }
          rootProject.name = "IntervalRunner"
          include(":app")
          EOF

          cat > app/build.gradle.kts <<'EOF'
          plugins { id("com.android.application"); id("org.jetbrains.kotlin.android") }

          android {
              namespace = "com.craig.intervalrunner"
              compileSdk = 34
              buildToolsVersion = "34.0.0"

              defaultConfig {
                  applicationId = "com.craig.intervalrunner"
                  minSdk = 24
                  targetSdk = 34
                  versionCode = 1
                  versionName = "1.0"
              }

              buildFeatures { compose = true }
              composeOptions { kotlinCompilerExtensionVersion = "1.5.14" }

              compileOptions {
                  sourceCompatibility = JavaVersion.VERSION_17
                  targetCompatibility = JavaVersion.VERSION_17
              }

              buildTypes {
                  getByName("release") {
                      isMinifyEnabled = false
                  }
              }
          }

          kotlin { jvmToolchain(17) }
          tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
              kotlinOptions.jvmTarget = "17"
          }

          dependencies {
              val composeBom = platform("androidx.compose:compose-bom:2024.06.00")
              implementation(composeBom); androidTestImplementation(composeBom)
              implementation("androidx.activity:activity-compose:1.9.0")
              implementation("androidx.compose.ui:ui")
              implementation("androidx.compose.material3:material3")
              implementation("androidx.compose.animation:animation")
              implementation("androidx.compose.ui:ui-tooling-preview")
              debugImplementation("androidx.compose.ui:ui-tooling")
          }
          EOF

          cat > gradle.properties <<'EOF'
          org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
          android.useAndroidX=true
          android.enableJetifier=false
          EOF

          cat > app/src/main/AndroidManifest.xml <<'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
            <application
                android:label="Interval Runner"
                android:icon="@mipmap/ic_launcher"
                android:roundIcon="@mipmap/ic_launcher_round"
                android:allowBackup="true">
              <activity
                  android:name=".MainActivity"
                  android:exported="true">
                <intent-filter>
                  <action android:name="android.intent.action.MAIN" />
                  <category android:name="android.intent.category.LAUNCHER" />
                </intent-filter>
              </activity>
            </application>
          </manifest>
          EOF

          cat > app/src/main/java/com/craig/intervalrunner/MainActivity.kt <<'EOF'
          // (your full Compose MainActivity.kt code here)
          EOF

          cat > app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml <<'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
              <background android:drawable="@android:color/black"/>
              <foreground android:drawable="@drawable/ic_dumbbell"/>
              <monochrome android:drawable="@drawable/ic_dumbbell"/>
          </adaptive-icon>
          EOF

          cat > app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml <<'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
              <background android:drawable="@android:color/black"/>
              <foreground android:drawable="@drawable/ic_dumbbell"/>
              <monochrome android:drawable="@drawable/ic_dumbbell"/>
          </adaptive-icon>
          EOF

          cat > app/src/main/res/drawable/ic_dumbbell.xml <<'EOF'
          <vector xmlns:android="http://schemas.android.com/apk/res/android"
              android:width="108dp"
              android:height="108dp"
              android:viewportWidth="24"
              android:viewportHeight="24">
              <path
                  android:fillColor="#FFFFFFFF"
                  android:pathData="M3,10h2v4H3v-4zM5,9h2v6H5V9zM7,10h2v4H7v-4zM9,11h6v2H9v-2zM15,10h2v4h-2v-4zM17,9h2v6h-2V9zM19,10h2v4h-2v-4z"/>
          </vector>
          EOF

      - name: Generate Gradle wrapper
        run: gradle wrapper --gradle-version 8.7

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: interval-runner-apk
          path: app/build/outputs/apk/**/*.apk
          if-no-files-found: error
